name: dungeon_world_data
homepage: https://github.com/chenasraf/dungeon_world_data
description: Data dump of Dungeon World classes, moves, equipment, and more
version: 2.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  quiver: ^2.0.1
  meta: ^1.1.0
  uuid: ^2.0.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.4
  dart_style: ^1.3.3
  path: ^1.6.4
