name: dungeon_world_data
homepage: https://github.com/DungeonPaper/dungeon_world_data
description: Data dump of Dungeon World classes, moves, equipment, and more. Also mirrored as NPM package.
version: 3.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.15.0-nullsafety.4
  meta: ^1.1.0
  quiver: ^3.0.1
  uuid: ^3.0.4

dev_dependencies:
  lints: ^1.0.1
  dart_style: ^2.0.3
  path: ^1.6.4
  test: ^1.6.4
