name: dungeon_world_data
homepage: https://github.com/DungeonPaper/dungeon_world_data
description: Data dump of Dungeon World classes, moves, equipment, and more. Also mirrored as NPM package.
version: 3.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  meta: ^1.10.0
  quiver: ^3.2.1
  uuid: ^4.0.0

dev_dependencies:
  lints: ^2.1.1
  dart_style: ^2.3.2
  path: ^1.8.3
  test: ^1.24.6

script_runner:
  scripts:
    - format: dart format --line-length 100
    - web:copy-data: dart scripts/parsers/dart_to_json.dart
    - web:build: cd web/src && yarn build
    - web:publish: cd web/src && npm publish -d ../build
