name: dungeon_world_data
author: Chen Asraf
homepage: https://github.com/chenasraf/dungeon_world_data
description: Data dump of Dungeon World classes, moves, equipment, and more
version: 1.3.4

environment:
  sdk: ">=1.8.0 <3.0.0"

dependencies:
  path: ^1.6.2
  quiver: ^2.0.1
  resource: ^2.1.5
  meta: ^1.1.0

dev_dependencies:
  test: ^1.6.4
